### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by mahmoudajawad** [VirgilSecurity/virgil-crypto-python#25]
What is the current status on supporting Python 3.8?  It seems `virgin-crypto` can be installed, however, dependency `virgin-crypto-lib` is not as it's marked for Python <= 3.7.

**Comment by kmuzychko** [comment]
Unfortunately, we don't support Python 3.8, because virgil-crypto-c binary does not have a build for it yet, and it is a mandatory dependency

**Comment by mahmoudajawad** [comment]
@Imelstorm, thanks for replying.

Python 3.8 didn't break anything about Python3.7, so `virgil-crypto-c` should be easily rebuilt for Python 3.8 and be published accordingly.

**Comment by mahmoudajawad** [comment]
Any update on this?

**Comment by kmuzychko** [comment]
Hello @mahmoudajawad `virgil-crypto-c` added support for Python3.8 and Python3.9

**Comment by mahmoudajawad** [comment]
Thanks a lot.
