### ISSUE TITLE
cannot install virgil-crypto-python

### ISSUE THREAD

**Issue by ghost** [VirgilSecurity/virgil-crypto-python#27]
hi, i tried on different environment to install python version, but i had same error on all platform

![image](https://user-images.githubusercontent.com/20506433/108116311-0eca0480-70a4-11eb-923d-f94038e9760c.png)
![image](https://user-images.githubusercontent.com/20506433/108116472-4b95fb80-70a4-11eb-8e24-81879aedc68f.png)
![image](https://user-images.githubusercontent.com/20506433/108116489-518bdc80-70a4-11eb-8045-a18bd0a7966e.png)

**Comment by kmuzychko** [comment]
Hello, what version of python do you use?

**Comment by ghost** [comment]
hello, i found problem, i use latest version of python 3.8, so i used python 3.6, and all work ok.
